### ISSUE TITLE
🚀  Roadmap 2.0

### ISSUE THREAD

**Issue by MarceauKa** [MarceauKa/shaark#96]
Hi all Shaark users! 👋

This is the roadmap for the 2.0 release and this is **work in progress** for now.

## Legend

- 🚧 Currently under development
- ✅ It's on my to-do list, but your contributions are needed
- 👥 I'd like to hear you on this, please share your feedback
- 💡 This is just an idea for now, feel free to share your ideas

### Core

- [ ] 🚧 Move to PHP 8.2 and battle test the codebase
- [ ] ✅ Totally new installer with a better integration of PDF and youtube-dl
- [ ] ✅ Moving from [Bootstrap 4.x](https://getbootstrap.com/docs/4.5/getting-started/introduction/) to [TailwindCSS](https://tailwindcss.com/)
- [ ] 👥 Major UX re-design
- [ ] 👥 Refactor the settings section, allowing app-wide and per-user customization
- [ ] ✅ Import from 1.x (of course)
- [ ] 💡 Better integration with docker and the Digital Ocean [marketplace](https://www.digitalocean.com/products/marketplace/)
- [ ] 💡 Allowing modules for content types and themes (with a brand new marketplace)

### Feature

- [ ] 👥 Post types will be a customizable aggregate of "link", "story", "album" and "chest" ; see [post types](#posts-type)
- [ ] 🚧 All link content will be able to get a screenshot of the given website
- [ ] 👥 Revamp the wall feature to be more usable with post types and the multi-users system
- [ ] 👥 Revisions and collaboration for posts
- [ ] ✅ Enhanced 2-FA auth with email, phone or google app
- [ ] 👥 REST API
- [ ] 💡 Webhooks and integration with zappier 
- [ ] 💡 Lock-on system: if the tab is idle for X minutes and/or your tab is changed you'll be asked for your password

### Post types

__WIP__

**Comment by MarceauKa** [comment]
Hi @wyred, @Pandry, @tuananhp-1844 and @kayschima. I need you 😇

**Comment by AuthorShin** [comment]
@MarceauKa Hello, any update on 2.0 version?

**Comment by MarceauKa** [comment]
Hello @AuthorShin, 2.0 is currently paused, I'll start again in few weeks

**Comment by AuthorShin** [comment]
Hello
Any update on this?

**Comment by AuthorShin** [comment]
Hello
@MarceauKa Any update on this?

**Comment by MarceauKa** [comment]
I'am currently working on the v2 :)

**Comment by AuthorShin** [comment]
Very happy to hear that :)
Keep up the good work 💪

**Comment by kamtschatka** [comment]
Better Docker integration is on the roadmap, but you asked for feedback:
Would be really great to have that! I have tried to use a docker image from dockerhub, but the whole config is currently built in in the Dockerfile (use the host mariadb and redis with fixed host names). For an easy deployment, usually those parameters are passed in via environment variables and then taken directly. This would make it possible to create a generic docker image and then people just point it to their sql database and their redis docker container.

Took me a few hours yesterday to get that running, because for some reason my changes to config.php and .env did not get used. It was totally worth it, shaark is REALLY great! There is literally nothing better available for self hosting.

I think if docker installation would be easy, then a lot more people would be using it (I am an unraid user and if something is in the store, that is a huge boost)

**Comment by MarceauKa** [comment]
@kamtschatka When I'll ready, can I keep in touch with you for a better Docker integration?

**Comment by kamtschatka** [comment]
absolutely!

**Comment by kamtschatka** [comment]
Some more feedback:
The organization of the posts is ok for smaller collections of posts, but for smaller collections I would like to have some structured way of organizing them.
A simple Tree structure where you can group them based on topics and then subtopics would be nice.
There is another tool that is similar to shaark, that solves it like this, which is quite helpful:
![image](https://user-images.githubusercontent.com/22147234/228670133-3fdc7995-3792-440a-8d1b-ebcf8cf9a39e.png)

**Comment by AuthorShin** [comment]
I wholeheartedly concur with @kamtschatka. It would be fantastic to have a simplified Docker installation process, where SQL and Redis are incorporated into the same container. This way, end-users could manage their environment variables and deal with only one container, making it incredibly convenient for those who wish to oversee their Docker instances through a management system or monitor their container's health. Additionally, users could also take advantage of auto-update functions and check for updates, further streamlining the process.

**Comment by philipp-koch** [comment]
Unfrotunately, I did not succeed to get this to run on my Synology NAS using Docker, even though a docker-compose.yml is provided. I would really love to see a simplified, integrated solution that would deploy (and possibly initialize) all containers needed. I've been looking quite some time now to find a good fit for my read-it-later self-hosting needs; from the screenshot, it seems that Shaark might be it—but since the demo instance doesn't work and there's very little activity, I'm not sure if this project even is still active/alive and whether it's realistic to hope for a new release?
